---
- name: download docs.opendatamap.net from GitHub
  git:
    repo: "https://github.com/OpenDataMap/docs.git"
    dest: "/var/www/opendatamap.net/docs.opendatamap.net"
    force: yes
    clone: yes

- name: install mkdocs
  pip:
    name:
      - "mkdocs"
      - "mkdocs-material"
    virtualenv: "/var/www/opendatamap.net/docs.opendatamap.net/.venv"
    virtualenv_command: "/usr/bin/python3 -m venv"
    state: present

- name: build docs.opendatamap.net
  shell: "/var/www/opendatamap.net/docs.opendatamap.net/.venv/bin/mkdocs build"
  args:
    chdir: "/var/www/opendatamap.net/docs.opendatamap.net"
