- name: download GPG Key from nginx repository
  apt_key:
    url: "https://nginx.org/keys/nginx_signing.key"
    state: present

- name: enable nginx repository
  apt_repository:
    repo: "deb https://nginx.org/packages/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }} nginx"
    state: present

- name: Install nginx
  apt:
    name: "nginx"
    state: present

- name: Create vhosts directory
  file:
    path: "/etc/nginx/vhosts"
    mode: 0755
    state: directory
    owner: root
    group: root

- name: Disable default site configuration
  file:
    dest: /etc/nginx/sites-enabled/default
    state: absent

- name: Install config
  template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"
  notify:
    - reload nginx