---
- name: Create .well-known/matrix directory in labcode.de
  file:
    path: /var/www/labcode.de/labcode.de/.well-known/matrix
    state: directory

- name: Create .well-known/matrix/server in labcode.de
  copy:
    src: well_known.json
    dest: /var/www/labcode.de/labcode.de/.well-known/matrix/server/index.json

- name: Create synapse data directory
  file:
    path: /volume/docker/labcode.de/matrix.labcode.de/data/
    state: directory
    owner: 991
    group: 991

- name: Add synapse homeserver config
  template:
    src: homeserver.yaml
    dest: /volume/docker/labcode.de/matrix.labcode.de/data/homeserver.yaml
    owner: 991
    group: 991

- name: Add synapse signing key
  copy:
    src: matrix.labcode.de.signing.key
    dest: /volume/docker/labcode.de/matrix.labcode.de/data/matrix.labcode.de.signing.key
    owner: 991
    group: 991

- name: Add synapse log config
  copy:
    src: matrix.labcode.de.log.config
    dest: /volume/docker/labcode.de/matrix.labcode.de/data/matrix.labcode.de.log.config
    owner: 991
    group: 991

- import_tasks: mautrix-telegram.yml

- name: Ensure docker container matrix.labcode.de-db exists
  docker_container:
    name: matrix.labcode.de-db
    image: postgres:11
    restart_policy: always
    volumes:
      - /volume/docker/labcode.de/matrix.labcode.de/db-data:/var/lib/postgresql/data
    env:
      POSTGRES_PASSWORD: "{{ synapse_db_password }}"
      POSTGRES_USER: "synapse"
      POSTGRES_DB: "synapse"
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"

- name: Ensure docker container matrix.labcode.de-app exists
  docker_container:
    name: matrix.labcode.de-app
    image: matrixdotorg/synapse:v1.12.0
    restart_policy: always
    links:
      - matrix.labcode.de-db:db
      - matrix.labcode.de-telegram:bridge-telegram
    volumes:
      - /volume/docker/labcode.de/matrix.labcode.de/data:/data
      - /volume/docker/labcode.de/matrix.labcode.de/appservices/telegram/registration.yaml:/telegram/registration.yaml
    labels:
      traefik.enable: "true"
      traefik.http.routers.matrix_labcode_de_http.rule: "Host(`matrix.labcode.de`)"
      traefik.http.routers.matrix_labcode_de_http.entryPoints: "http"
      traefik.http.routers.matrix_labcode_de_http.middlewares: "https_redirect@file"
      traefik.http.routers.matrix_labcode_de_https.rule: "Host(`matrix.labcode.de`)"
      traefik.http.routers.matrix_labcode_de_https.entryPoints: "https"
      traefik.http.routers.matrix_labcode_de_https.tls.certresolver: "le_http"
      traefik.http.services.matrix_labcode_de-app.loadbalancer.server.port: "8008"