---
- name: Add mautrix-telegram config to host
  template:
    src: "mautrix-telegram/config.yaml"
    dest: "/volume/docker/labcode.de/matrix.labcode.de/appservices/telegram/config.yaml"

- name: Add mautrix-telegram registration config to host
  template:
    src: "mautrix-telegram/registration.yaml"
    dest: "/volume/docker/labcode.de/matrix.labcode.de/appservices/telegram/registration.yaml"

- name: Ensure docker container matrix.labcode.de-telegram exists
  docker_container:
    name: matrix.labcode.de-telegram
    image: dock.mau.dev/tulir/mautrix-telegram:v0.7.1
    restart_policy: always
    volumes:
      - /volume/docker/labcode.de/matrix.labcode.de/appservices/telegram:/data