---
- name: Add/Modify DNS record for git.labcode.dev
  cloudflare_dns:
    account_email: "{{ cloudflare_api_email }}"
    account_api_token: "{{ cloudflare_api_token }}"
    record: "git"
    value: "{{ ansible_fqdn }}"
    type: CNAME
    zone: "labcode.dev"
    state: present

- name: Create /volume/docker/labcode.dev/git.labcode.dev/gitea/conf directory
  file:
    path: '/volume/docker/labcode.dev/git.labcode.dev/data/gitea/conf'
    state: directory
    recurse: yes
    owner: "1000"
    group: "1000"

- name: Add Gitea configuration file
  template:
    src: conf_app.ini.j2
    dest: /volume/docker/labcode.dev/git.labcode.dev/data/gitea/conf/app.ini
    owner: "1000"
    group: "1000"

- name: Upload SSH key
  copy:
    content: "{{ ssh_deploy_key }}"
    dest: /volume/docker/labcode.dev/git.labcode.dev/gitea_ssh_deploy_key
    owner: "1000"
    group: "1000"
    mode: "400"

- name: Create/launch docker container git.labcode.dev-app
  docker_container:
    image: gitea/gitea:1
    name: git.labcode.dev-app
    restart_policy: always
    volumes:
      - /volume/docker/labcode.dev/git.labcode.dev/data:/data
      - /volume/docker/labcode.dev/git.labcode.dev/gitea_ssh_deploy_key:/gitea_ssh_deploy_key
    ports:
      - "222:22"
    labels:
      traefik.enable: "true"
      traefik.http.routers.git-labcode-dev_http.rule: "Host(`git.labcode.dev`) || Host(`git.lbcd.dev`) || Host(`git.labcode.de`)"
      traefik.http.routers.git-labcode-dev_http.entryPoints: "http"
      traefik.http.routers.git-labcode-dev_http.middlewares: "https_redirect@file"
      traefik.http.routers.git-labcode-dev_https.rule: "Host(`git.labcode.dev`) || Host(`git.lbcd.dev`) || Host(`git.labcode.de`)"
      traefik.http.routers.git-labcode-dev_https.entryPoints: "https"
      traefik.http.routers.git-labcode-dev_https.tls.certresolver: "le_http"
      traefik.http.services.git-labcode-dev-app.loadbalancer.server.port: "3000"

- name: Import git.labcode.dev backup
  include_tasks: backup.yml