---
- name: download labcode.de from GitHub
  git:
    repo: 'https://github.com/labcode-de/labcode.de.git'
    dest: /var/www/labcode.de/labcode.de
    force: yes

- name: Create/launch docker container labcode.de-web
  docker_container:
    image: nginx:latest
    name: labcode.de-web
    volumes:
      - /var/www/labcode.de/labcode.de:/usr/share/nginx/html
    restart_policy: always
    labels:
      traefik.enable: "true"
      traefik.http.routers.labcode-de_http.rule: "Host(`labcode.de`)"
      traefik.http.routers.labcode-de_http.entryPoints: "http"
      traefik.http.routers.labcode-de_http.middlewares: "https_redirect@file"
      traefik.http.routers.labcode-de_https.rule: "Host(`labcode.de`)"
      traefik.http.routers.labcode-de_https.entryPoints: "https"
      traefik.http.routers.labcode-de_https.tls.certresolver: "le_tls"