---
- name: Add/Modify DNS record for labcode.de
  cloudflare_dns:
    account_email: "{{ cloudflare_api_email }}"
    account_api_token: "{{ cloudflare_api_token }}"
    record: "@"
    value: "{{ ansible_fqdn }}"
    type: CNAME
    zone: "labcode.de"
    state: present

- name: Add/Modify DNS record for www.labcode.de
  cloudflare_dns:
    account_email: "{{ cloudflare_api_email }}"
    account_api_token: "{{ cloudflare_api_token }}"
    record: "www"
    value: "{{ ansible_fqdn }}"
    type: CNAME
    zone: "labcode.de"
    state: present

- name: download labcode.de from GitHub
  git:
    repo: 'https://github.com/labcode-de/labcode.de.git'
    dest: /var/www/labcode.de/labcode.de
    force: yes

- name: Add nginx config for labcode.de
  copy:
    src: nginx_vhost.conf
    dest: /etc/nginx/vhosts/labcode_de.conf
  notify:
    - reload nginx

- name: Add traefik config for labcode.de
  template:
    src: traefik.yml
    dest: /volume/docker/traefik/config/dynamic/labcode_de.yml