---
- name: Create synapse data directory
  file:
    path: "/opt/matrix-synapse/data/"
    state: directory
    owner: "synapse"
    group: "synapse"

- name: Install synapse pip package
  pip:
    name: "matrix-synapse==1.17.0"
    virtualenv: "/opt/matrix-synapse/.venv"
    virtualenv_command: "/usr/bin/python3 -m venv"
    state: present
  become_user: synapse

- name: Install postgresql-client apt packages
  apt:
    name:
      - postgresql-client
      - libpq-dev
    state: present

- name: Install psycopg2 pip package
  pip:
    name: "psycopg2"
    virtualenv: "/opt/matrix-synapse/.venv"
    virtualenv_command: "/usr/bin/python3 -m venv"
    state: present
  become_user: synapse

- name: Add systemd service file for matrix-synapse
  copy:
    src: "matrix-synapse.service"
    dest: "/etc/systemd/system/matrix-synapse.service"

- name: Ensure matrix-synapse systemd service is enabled and running
  systemd:
    name: "matrix-synapse"
    daemon_reload: yes
    enabled: yes
    state: started
