---
- name: Create mautrix-telegram config directory
  file:
    path: "/opt/matrix-synapse/appservices/telegram/"
    recurse: yes
    state: directory
    owner: "synapse"
    group: "synapse"

- name: Add mautrix-telegram example config to host
  copy:
    src: "mautrix-telegram-example-config.yml"
    dest: "/opt/matrix-synapse/appservices/telegram/example-config.yaml"
    owner: "synapse"
    group: "synapse"

- name: Add mautrix-telegram config to host
  template:
    src: "mautrix-telegram/config.yaml"
    dest: "/opt/matrix-synapse/appservices/telegram/config.yaml"
    owner: "synapse"
    group: "synapse"

- name: Add mautrix-telegram registration config to host
  template:
    src: "mautrix-telegram/registration.yaml"
    dest: "/opt/matrix-synapse/appservices/telegram/registration.yaml"
    owner: "synapse"
    group: "synapse"

- name: Install mautrix-telegram pip package
  pip:
    name: "mautrix-telegram==0.7.2"
    virtualenv: "/opt/matrix-synapse/.venv"
    virtualenv_command: "/usr/bin/python3 -m venv"
    state: present
  register: mautrix_telegram_pip_install
  become_user: synapse

#- name: Create mautrix-telegram database
#  shell: "/opt/matrix-synapse/.venv/bin/alembic -x config=/opt/matrix-synapse/appservices/telegram/config.yaml upgrade head"
#  when: mautrix_telegram_pip_install.changed
#  become_user: synapse

- name: Add systemd service file for mautrix-telegram
  copy:
    src: "mautrix-telegram.service"
    dest: "/etc/systemd/system/mautrix-telegram.service"

- name: Ensure mautrix-telegram systemd service is enabled and running
  systemd:
    name: "mautrix-telegram"
    daemon_reload: yes
    enabled: yes
    state: started