---
- name: Get hostname of web-nginx-server
  set_fact:
    web_nginx_hostname: "{{ item }}"
  when: hostvars[item].ansible_domain == ansible_domain
  with_items: "{{ groups.web_nginx }}"

- name: Get hostname of web-services-server
  set_fact:
    web_services_hostname: "{{ item }}"
  when: hostvars[item].ansible_domain == ansible_domain
  with_items: "{{ groups.web_services }}"

- name: Get hostname of web-drone-ci-server
  set_fact:
    drone_ci_hostname: "{{ item }}"
  when: hostvars[item].ansible_domain == ansible_domain
  with_items: "{{ groups.drone_ci }}"

- name: Get hostname of web-iam-server
  set_fact:
    iam_hostname: "{{ item }}"
  when: hostvars[item].ansible_domain == ansible_domain
  with_items: "{{ groups.iam }}"

- name: Add dynamic traefik configs to server
  template:
    dest: "/opt/traefik/config/dynamic/{{ item.path }}"
    src: "{{ item.path }}"
    owner: traefik
    group: traefik
  with_filetree: 'templates/'
