- name: Create/run drone-server docker container
  docker_container:
    name: drone-server
    image: drone/drone:1.7.0
    restart_policy: always
    ports:
      - "40000:80"
    volumes:
      - "/opt/drone:/data"
    env:
      DRONE_GITEA_SERVER: "https://git.labcode.dev"
      DRONE_GITEA_CLIENT_ID: "{{ drone_ci_client_id }}"
      DRONE_GITEA_CLIENT_SECRET: "{{ drone_ci_client_secret }}"
      DRONE_RPC_SECRET: "{{ drone_rpc_secret }}"
      DRONE_SERVER_HOST: "ci.labcode.dev"
      DRONE_SERVER_PROTO: "https"
      DRONE_DATABASE_DRIVER: "postgres"
      DRONE_DATABASE_DATASOURCE: "postgres://drone:{{ drone_db_password }}@10.151.10.5:5432/drone?sslmode=disable"
      DRONE_DATABASE_SECRET: "{{ drone_db_secret }}"
      DRONE_USER_CREATE: "username:labcode,admin:true"

- name: Create/run drone-runner01 docker container
  docker_container:
    name: drone-runner01
    image: drone/drone-runner-docker:1.2.1
    restart_policy: always
    ports:
      - "40001:3000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    env:
      DRONE_RPC_PROTO: "https"
      DRONE_RPC_HOST: "ci.labcode.dev"
      DRONE_RPC_SECRET: "{{ drone_rpc_secret }}"
      DRONE_RUNNER_CAPACITY: "2"
      DRONE_RUNNER_NAME: "runner01.ci.labcode.dev"