---
borg_encryption_passphrase: "{{ lookup('passwordstore', 'infra/host/{{ ansible_host }}/backup_encryption') }}"
borg_repository: "backup@helene.int.sig.de.labcode.de:/mnt/backup/repos/{{ ansible_host }}"
borg_ssh_command: "ssh -o StrictHostKeyChecking=no -p 1880 -i /root/.ssh/backup_ssh_key "
borgmatic_large_repo: false
borg_source_directories:
  - /home
  - /var
  - /opt
  - /etc
  - /root
borg_exclude_patterns:
  - /var/cache
  - /var/lock
  - /var/spool
  - /var/log
  - /var/lib/docker/image
  - node_modules
  - .venv
borg_retention_policy:
  keep_daily: 7
  keep_weekly: 4
  keep_monthly: 3
