---
coredns_config_file: "../files/coredns/Corefile.j2"
coredns_zone_files_paths:
  - "../files/coredns/zones/*"

powerdns_base_directory: "/var/lib/powerdns"

pdns_install_repo: "{{ pdns_auth_powerdns_repo_44 }}"
pdns_config:
  master: yes
  allow-axfr-ips: "213.239.242.238,213.133.105.6,193.47.99.3,216.218.133.2,2001:470:600::2,127.0.0.1,::1"
  dnsupdate: yes
  allow-dnsupdate-from: "fd8f:d15b:9f40::/48"
  expand-alias: yes
  resolver: "2606:4700:4700::1111,2606:4700:4700::1001,1.1.1.1,8.8.8.8"

powerdns_bind_dnssec_database_file: "{{ powerdns_base_directory }}/bind/dnssec-db.sqlite3"

pdns_backends:
  bind:
    config: "{{ powerdns_base_directory }}/bind/named.conf"
    check-interval: 60
    dnssec-db: "{{ powerdns_bind_dnssec_database_file }}"
  'gsqlite3:dyndns':
    database: "{{ powerdns_base_directory }}/sqlite3.db"

pdns_backends_packages:
  bind: pdns-backend-bind
  geo: pdns-backend-geo
  geoip: pdns-backend-geoip
  gmysql: pdns-backend-mysql
  gpgsql: pdns-backend-pgsql
  gsqlite3: pdns-backend-sqlite3
  ldap: pdns-backend-ldap
  lmdb: pdns-backend-lmdb
  lua: pdns-backend-lua
  mydns: pdns-backend-mydns
  pipe: pdns-backend-pipe
  remote: pdns-backend-remote
  tinydns: pdns-backend-tinydns

pdns_bind_tsig_keys:
  - { name: "he.net-powerdns", secret: "{{ lookup('passwordstore', 'infra/service/dns/tsig/he.net-powerdns') }}", algorithm: "{{ lookup('passwordstore', 'infra/service/dns/tsig/he.net-powerdns subkey=algorithm') }}" }

pdns_bind_domains_tsig:
  - { domain: lbcd.dev, key: "he.net-powerdns" }
  - { domain: labcode.de, key: "he.net-powerdns" }
  - { domain: em0lar.de, key: "he.net-powerdns" }
  - { domain: emolar.de, key: "he.net-powerdns" }
  - { domain: labcode.dev, key: "he.net-powerdns" }
  - { domain: leomaroni.de, key: "he.net-powerdns" }
  - { domain: opendatamap.net, key: "he.net-powerdns" }

