---
coredns_config_file: "../files/coredns/Corefile.j2"
coredns_zone_files_paths:
  - "../files/coredns/zones/*"

powerdns_base_directory: "/var/lib/powerdns"

pdns_install_repo: "{{ pdns_auth_powerdns_repo_44 }}"
pdns_config:
  master: yes
  allow-axfr-ips: "213.239.242.238,213.133.105.6,193.47.99.3,216.218.133.2,2001:470:600::2,127.0.0.1,::1,78.46.251.132,95.217.163.175,212.227.174.29,2a01:4f8:c0c:34bc::1,2a01:4f9:c010:7b6e::1,2001:8d8:1800:30e::1"
  dnsupdate: yes
  allow-dnsupdate-from: "fd8f:d15b:9f40::/48"
  expand-alias: yes
  resolver: "::1"
  slave: yes
  superslave: yes

powerdns_bind_dnssec_database_file: "{{ powerdns_base_directory }}/bind/dnssec-db.sqlite3"

pdns_backends:
  bind:
    config: "{{ powerdns_base_directory }}/bind/named.conf"
    check-interval: 60
    dnssec-db: "{{ powerdns_bind_dnssec_database_file }}"
  gsqlite3:
    database: "{{ powerdns_base_directory }}/sqlite3.db"
    dnssec: true

pdns_backends_packages:
  bind: pdns-backend-bind
  geo: pdns-backend-geo
  geoip: pdns-backend-geoip
  gmysql: pdns-backend-mysql
  gpgsql: pdns-backend-pgsql
  gsqlite3: pdns-backend-sqlite3
  ldap: pdns-backend-ldap
  lmdb: pdns-backend-lmdb
  lua: pdns-backend-lua
  mydns: pdns-backend-mydns
  pipe: pdns-backend-pipe
  remote: pdns-backend-remote
  tinydns: pdns-backend-tinydns

pdns_bind_tsig_keys:
  - { name: "he.net-powerdns", secret: "{{ lookup('passwordstore', 'infra/service/dns/tsig/he.net-powerdns') }}", algorithm: "{{ lookup('passwordstore', 'infra/service/dns/tsig/he.net-powerdns subkey=algorithm') }}" }
  - { name: "dnscluster", secret: "{{ lookup('passwordstore', 'infra/service/dns/tsig/dnscluster') }}", algorithm: "{{ lookup('passwordstore', 'infra/service/dns/tsig/dnscluster subkey=algorithm') }}" }

pdns_bind_domains_tsig:
  - { domain: lbcd.dev, key: "dnscluster" }
  - { domain: labcode.de, key: "dnscluster" }
  - { domain: em0lar.de, key: "dnscluster" }
  - { domain: em0lar.dev, key: "dnscluster" }
  - { domain: emolar.de, key: "dnscluster" }
  - { domain: labcode.dev, key: "dnscluster" }
  - { domain: leomaroni.de, key: "dnscluster" }
  - { domain: opendatamap.net, key: "dnscluster" }

powerdns_database_file: /var/lib/powerdns/sqlite3.db
powerdns_tsig_key_name: "dnscluster"
powerdns_tsig_key: "{{ lookup('passwordstore', 'infra/service/dns/tsig/dnscluster') }}"
powerdns_primary_ips:
  - 78.46.251.132
  - 2a01:4f8:c0c:34bc::1
powerdns_secondary_names:
  - ns.labcode.de
powerdns_config_directory: "/etc/powerdns"
