- name: Install certbot and certbot-dns-cloudflare
  pip:
    name: ['certbot', 'wheel', 'certbot-dns-cloudflare']
    virtualenv: /volume/docker/letsencrypt/.venv
    virtualenv_command: /usr/bin/python3 -m venv

- name: Create Let's Encrypt directory
  file:
    path: "/etc/letsencrypt"
    state: directory

- name: Create Cloudflare API key file
  copy:
    dest: "/etc/letsencrypt/dnscloudflare.ini"
    mode: 0600
    content: |
      dns_cloudflare_api_key = {{ cloudflare_api_key }}
      dns_cloudflare_email = {{ cloudflare_email }}

- name: Generate Certificate
  shell:
    executable: /bin/bash
    cmd: source /volume/docker/letsencrypt/.venv/bin/activate && certbot certonly -d {{ ansible_fqdn }} -d mail.bechilli.de -d mail.hicologne.com -d mail.labcode.de -d mail.labcode.dev -d mail.lbcd.dev -d mail.leomaroni.de -d mail.opendatamap.net --dns-cloudflare --agree-tos --email webmaster@labcode.de -n --dns-cloudflare-credentials /etc/letsencrypt/dnscloudflare.ini --server https://acme-v02.api.letsencrypt.org/directory

- name: remove certbot standard cronjob
  file:
    path: /etc/cron.d/certbot
    state: absent

- name: Add renew script to server
  template:
    src: "renew.sh"
    dest: "/etc/letsencrypt/renew.sh"
    mode: "+x"

- name: Add Cronjob doe renewing certificates every month
  cron:
    name: renew letsencrypt certs
    special_time: monthly
    job: "/etc/letsencrypt/renew.sh > /dev/null"
    user: root