---
backup_cifs_mount_password: "{{ lookup('passwordstore', 'infra/host/encladus.int.sig.de/backup_user') }}"
backup_pool_path: "/mnt/backup/repos/synced"
backup_auth_users:
  - host: rhea.int.sig.de.labcode.de
    key: "{{ lookup('passwordstore', 'infra/host/rhea.int.sig.de.labcode.de/backup_ssh_key subkey=public') }}"
  - host: titan.int.sig.de.labcode.de
    key: "{{ lookup('passwordstore', 'infra/host/titan.int.sig.de.labcode.de/backup_ssh_key subkey=public') }}"
  - host: hyperion.int.sig.de.labcode.de
    key: "{{ lookup('passwordstore', 'infra/host/hyperion.int.sig.de.labcode.de/backup_ssh_key subkey=public') }}"
  - host: dns.int.sig.de.labcode.de
    key: "{{ lookup('passwordstore', 'infra/host/dns.int.sig.de.labcode.de/backup_ssh_key subkey=public') }}"
  - host: cetus.het.hel.fi.labcode.de
    key: "{{ lookup('passwordstore', 'infra/host/cetus.het.hel.fi.labcode.de/backup_ssh_key subkey=public') }}"
  - host: phoebe.int.sig.de.labcode.de
    key: "{{ lookup('passwordstore', 'infra/host/phoebe.int.sig.de.labcode.de/backup_ssh_key subkey=public') }}"
  - host: janus.ion.rhr.de.labcode.de
    key: "{{ lookup('passwordstore', 'infra/host/janus.ion.rhr.de.labcode.de/backup_ssh_key subkey=public') }}"
  - host: mimas.int.sig.de.labcode.de
    key: "{{ lookup('passwordstore', 'infra/host/mimas.int.sig.de.labcode.de/backup_ssh_key subkey=public') }}"
    pool_path: "/mnt/backup/repos/unsynced"
  - host: mars.het.nue.de.fahrplandatengarten.de
    key: "{{ lookup('passwordstore', 'infra/host/mars.het.nue.de.fahrplandatengarten.de/backup_ssh_key subkey=public') }}"

b2_sync_account: "{{ lookup('passwordstore', 'infra/host/helene.int.sig.de.labcode.de/backblaze_b2 subkey=account') }}"
b2_sync_key: "{{ lookup('passwordstore', 'infra/host/helene.int.sig.de.labcode.de/backblaze_b2') }}"
b2_sync_path: "{{ backup_pool_path }}"
b2_sync_bucket_name: "labcode-backup"
