---
- name: Prevent asking for interactive input in nextcloud.sh by removing read prompts.
  replace:
    path: "/docker/mailcow/helper-scripts/nextcloud.sh"
    regexp: "^[ ]*read -"
    replace: "  : #read -"
    backup: yes

- name: Prevent errors due to docker tty running non-interactive.
  replace:
    path: "/docker/mailcow/helper-scripts/nextcloud.sh"
    regexp: "docker exec -it"
    replace: "docker exec -i"

- name: Prevent curl progress bar; make silent downloads.
  replace:
    path: "/docker/mailcow/helper-scripts/nextcloud.sh"
    regexp: "curl -L#"
    replace: "curl -Ls"

- name: Set subdomain name in nextcloud.sh.
  replace:
    path: "/docker/mailcow/helper-scripts/nextcloud.sh"
    regexp: "NC_SUBD=$"
    replace: "NC_SUBD=cloud.labcode.party"

## TODO:
# ADMIN_NC_PASS=$(</dev/urandom tr -dc A-Za-z0-9 | head -c 28)
# add password after the line above
# ADMIN_NC_PASS="{ my_nc_passwoord }"

- name: Run NextCloud installer (only runs once).
  shell: ./nextcloud.sh --install
  args:
    executable: /bin/bash
    chdir: "/docker/mailcow/helper-scripts/"
    creates: "/docker/mailcow/data/web/nextcloud/index.php"
  environment:
    NC_CONT_FAIL: "yes"