- name: Create traefik config directory
  file:
    path: "/volume/docker/traefik/config"
    state: directory

- name: Add traefik static config to host
  template:
    dest: "/volume/docker/traefik/config/traefik.yml"
    src: "traefik_static.yml.j2"

- name: Add traefik dynamic config to host
  template:
    dest: "/volume/docker/traefik/config/dynamic.yml"
    src: "traefik_dynamic.yml.j2"

- name: Run Traefik Docker container
  docker_container:
    name: traefik
    image: traefik:v2.0
    command: --api.insecure=true --providers.docker
    restart_policy: always
    networks_cli_compatible: yes
    ports:
      - "80:80"
      - "443:443"
      - "127.0.0.1:8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /volume/docker/traefik/config:/etc/traefik/
      - /volume/docker/traefik/letsencrypt:/letsencrypt
    networks:
      - name: bridge
      - name: mailcow_mailcow-network