---
- name: Create backup directory
  file:
    path: "/volume/backup/mailcow/"
    state: directory
    owner: backup
    group: backup

- name: Upload mailcow-backup script
  template:
    src: "backup.sh.j2"
    dest: "{{ mailcow_root_path }}/backup.sh"
    mode: "+x"

- name: Ensure the mailcow-backup script runs every day at 1am
  cron:
    name: "backup: mailcow"
    hour: "1"
    minute: "0"
    job: "{{ mailcow_root_path }}/backup.sh > /dev/null"