---
- name: Add/Modify mail. CNAME DNS records
  cloudflare_dns:
    account_email: "{{ cloudflare_api_email }}"
    account_api_token: "{{ cloudflare_api_token }}"
    record: "mail.{{ item }}"
    value: "{{ ansible_fqdn }}"
    type: CNAME
    zone: "{{ item.split('.')[-2] }}.{{ item.split('.')[-1] }}"
    state: present
  with_items:
    - bechilli.de
    - fahrplandatengarten.de
    - hicologne.com
    - infra.labcode.de
    - labcode.de
    - labcode.dev
    - lbcd.dev
    - leomaroni.de
    - opendatamap.net
    - services.leomaroni.de

- name: Add/Modify MX DNS records
  cloudflare_dns:
    account_email: "{{ cloudflare_api_email }}"
    account_api_token: "{{ cloudflare_api_token }}"
    record: "{{ '@' if item.split('.') | length == 2 else item }}"
    value: "{{ ansible_fqdn }}"
    type: MX
    zone: "{{ item.split('.')[-2] }}.{{ item.split('.')[-1] }}"
    state: present
  with_items:
    - bechilli.de
    - fahrplandatengarten.de
    - hicologne.com
    - infra.labcode.de
    - labcode.de
    - labcode.dev
    - lbcd.dev
    - leomaroni.de
    - opendatamap.net
    - services.leomaroni.de

- name: Add/Modify autoconfig/autodiscover DNS records
  cloudflare_dns:
    account_email: "{{ cloudflare_api_email }}"
    account_api_token: "{{ cloudflare_api_token }}"
    record: "{{ item }}"
    value: "{{ ansible_fqdn }}"
    type: CNAME
    zone: "{{ item.split('.')[-2] }}.{{ item.split('.')[-1] }}"
    state: present
  with_items:
    - autoconfig.bechilli.de
    - autoconfig.fahrplandatengarten.de
    - autoconfig.hicologne.com
    - autoconfig.infra.labcode.de
    - autoconfig.labcode.de
    - autoconfig.labcode.dev
    - autoconfig.lbcd.dev
    - autoconfig.leomaroni.de
    - autoconfig.opendatamap.net
    - autoconfig.services.leomaroni.de
    - autodiscover.bechilli.de
    - autodiscover.fahrplandatengarten.de
    - autodiscover.hicologne.com
    - autodiscover.infra.labcode.de
    - autodiscover.labcode.de
    - autodiscover.labcode.dev
    - autodiscover.lbcd.dev
    - autodiscover.leomaroni.de
    - autodiscover.opendatamap.net
    - autodiscover.services.leomaroni.de

- name: Add/Modify autodiscover SRV DNS record
  cloudflare_dns:
    account_email: "{{ cloudflare_api_email }}"
    account_api_token: "{{ cloudflare_api_token }}"
    service: "_autodiscover{{ '.' if item.split('.') | length > 2 }}{{ item.split('.')[:item.split('.') | length -2] | join('.') }}"
    proto: tcp
    port: 443
    priority: 1
    weight: 10
    value: "{{ ansible_fqdn }}"
    type: SRV
    zone: "{{ item.split('.')[-2] }}.{{ item.split('.')[-1] }}"
    state: present
  with_items:
    - bechilli.de
    - fahrplandatengarten.de
    - hicologne.com
    - infra.labcode.de
    - labcode.de
    - labcode.dev
    - lbcd.dev
    - leomaroni.de
    - opendatamap.net
    - services.leomaroni.de

- name: Add/Modify SPF DNS record
  cloudflare_dns:
    account_email: "{{ cloudflare_api_email }}"
    account_api_token: "{{ cloudflare_api_token }}"
    record: "{{ item }}"
    value: "v=spf1 a mx ~all"
    type: TXT
    zone: "{{ item.split('.')[-2] }}.{{ item.split('.')[-1] }}"
    state: present
  with_items:
    - bechilli.de
    - fahrplandatengarten.de
    - hicologne.com
    - infra.labcode.de
    - labcode.de
    - labcode.dev
    - lbcd.dev
    - leomaroni.de
    - opendatamap.net
    - services.leomaroni.de