---
- name: Clone mailcow-dockerized from GitHub
  git:
    repo: https://github.com/mailcow/mailcow-dockerized
    version: master
    dest: /docker/mailcow
    update: no

- name: Create directory for certificates in mailcow
  file:
    path: "/docker/mailcow/data/assets/ssl/"
    state: directory

- name: Copy SSL example dhparams file in mailcow
  copy:
    src: "/docker/mailcow/data/assets/ssl-example/dhparams.pem"
    dest: "/docker/mailcow/data/assets/ssl/dhparams.pem"
    remote_src: yes

- name: Put LE certificate in mailcow
  copy:
    src: "/etc/letsencrypt/live/{{ ansible_fqdn }}/fullchain.pem"
    dest: "/docker/mailcow/data/assets/ssl/cert.pem"
    remote_src: yes

- name: Put LE certificate key in mailcow
  copy:
    src: "/etc/letsencrypt/live/{{ ansible_fqdn }}/privkey.pem"
    dest: "/docker/mailcow/data/assets/ssl/key.pem"
    remote_src: yes

- name: Create mailcow.conf from template
  template:
    src: mailcow.conf.j2
    dest: "/docker/mailcow/mailcow.conf"

- name: Add docker-compose.override.yml from template
  template:
    src: docker-compose.override.yml.j2
    dest: "/docker/mailcow/docker-compose.override.yml"

- name: Create folders for docker volumes part 1
  file:
    path: /volume/docker/data/mailcow/vmail
    recurse: true
    state: directory

- name: Create folders for docker volumes part 2
  file:
    path: /volume/docker/data/mailcow/vmail_attachments
    recurse: true
    state: directory

- name: Create folders for docker volumes part 3
  file:
    path: /volume/docker/data/mailcow/mysql
    recurse: true
    state: directory

- name: Pull and start mailcow docker containers
  docker_compose:
    project_src: "/docker/mailcow"
    pull: yes
    state: present
