---
- name: Clone mailcow-dockerized from GitHub
  git:
    repo: https://github.com/mailcow/mailcow-dockerized
    version: master
    dest: "{{ mailcow_root_path }}/repo"
    update: no

- name: Create mailcow.conf from template
  template:
    src: mailcow.conf.j2
    dest: "{{ mailcow_root_path }}/repo/mailcow.conf"
    backup: yes

- name: Pull and start mailcow docker containers
  docker_compose:
    project_src: "/{{ mailcow_root_path }}/repo"
    pull: yes
    state: present

- import_tasks: backup.yml
