- name: Install gunicorn
  pip:
    name: gunicorn==20.0.4
    state: present
    virtualenv: /opt/wifi_radius_manager/.venv

- name: Add Gunicorn service template
  copy:
    src: gunicorn.service
    dest: /etc/systemd/system/wifi_radius_manager_gunicorn.service

- name: Add tmpfiles/gunicorn config template
  template:
    src: tmpfiles_gunicorn.conf.j2
    dest: /etc/tmpfiles.d/wifi_radius_manager_gunicorn.conf

- name: Ensure gunicorn socket service is enabled and started
  systemd:
    name: wifi_radius_manager_gunicorn.service
    daemon_reload: yes
    enabled: yes
    state: started
