---
- name: create wifi_radius_manager folder
  file:
    path: "/opt/wifi_radius_manager"
    owner: "freerad"
    group: "freerad"
    recurse: yes
    state: directory

- name: Clone repository from GitHub
  git:
    repo: "https://git.labcode.dev/em0lar/wifi_radius_manager.git"
    dest: "/opt/wifi_radius_manager"
    force: yes
    recursive: yes
  become_user: "freerad"
  notify:
    - Restart gunicorn service

- name: Install pip requirements
  pip:
    requirements: "/opt/wifi_radius_manager/requirements.txt"
    virtualenv: "/opt/wifi_radius_manager/.venv"
    virtualenv_command: "/usr/bin/python3 -m venv"
    extra_args: "--upgrade"
  become_user: "freerad"

- name: copy app configuration
  template:
    src: ".env.j2"
    dest: "/opt/wifi_radius_manager/.env"
  notify:
    - Restart gunicorn service

- name: Install required apt packages
  apt:
    name:
      - xmlsec1

- include: gunicorn.yml