---
dn42_wg_private_key: "{{ lookup('passwordstore', 'infra/host/' + ansible_fqdn + '/dn42/default') }}"

dn42_local_subnet_v4: "172.20.209.0/27"
dn42_local_subnet_v6: "fdf3:bd28:d90b::/48"
dn42_local_v4: "172.20.209.1"
dn42_local_v6: "fdf3:bd28:d90b::1"
dn42_local_as: "4242420215"

dn42_configure_linux_network_table: yes

dn42_enable_roa: yes

dn42_pingfinder_enable: no
dn42_pingfinder_uuid: "{{ lookup('passwordstore', 'infra/host/' + ansible_fqdn + '/dn42/pingfinder') }}"

dn42_peers:
  - name: "n0emis"
    as: "4242420197"
    v4: "172.20.190.96"  # We are doing multiprotocol
    v6: "fe80::42:42:1"
    if:
      v4: "172.20.209.1"
      v6: "fe80::42:1"
    wg:
      port: "50197"
      endpoint: "himalia.dn42.n0emis.eu:50215"
      pubkey: "L4+/5r6LhlLQbEX0FgVmeZCciLRratsUbakVV0GTLCg="
      privkey: "{{ lookup('passwordstore', 'infra/host/' + ansible_fqdn + '/dn42/n0emis') }}"
    multiprotocol: yes
  - name: "margau"
    as: "4242421280"
    v4: "172.22.161.106"
    v6: "fde3:4c0d:2836:ff00::16"
    if:
      v4: "172.20.209.1"
      v6: "fde3:4c0d:2836:ff00::17"
    wg:
      port: "51280"
      endpoint: "wg1.margau.ipv6.church:51828"
      pubkey: "x0ZbO99FI4GCmqiCdQbCG26z0ecj4n1UrdKIR4M1jDQ="
      privkey: "{{ lookup('passwordstore', 'infra/host/' + ansible_fqdn + '/dn42/margau') }}"
    multiprotocol: yes
  - name: "yurachan"
    as: "4242422464"
    v4: "169.254.24.64"
    v6: "fe80::2464"
    if:
      v4: "172.20.209.1"
      v6: "fe80::42:1"
    wg:
      port: "52464"
      endpoint: "fra.dneo.moeternet.com:20215"
      pubkey: "qIhJZf6mTruzO4GTCUrJnLqs9ID4TI1GctRhaRilBkg="
      privkey: "{{ lookup('passwordstore', 'infra/host/' + ansible_fqdn + '/dn42/yurachan') }}"
    multiprotocol: yes
  - name: "e1mo"
    as: "4242420565"
    v4: "172.20.229.160"
    v6: "fe80::43:1"
    if:
      v4: "172.20.209.1"
      v6: "fe80::43:42:1"
    wg:
      port: "50565"
      endpoint: "de-fra1.dn42.net.dont-break.it:20215"
      pubkey: "LjXwHWJXz5koYyVsZ0UjSHr/zpxIUz/dPzucJSFSDUg="
      privkey: "{{ lookup('passwordstore', 'infra/host/' + ansible_fqdn + '/dn42/e1mo') }}"
    multiprotocol: yes
  - name: "moecast"
    as: "4242420604"
    v4: "172.23.89.3"
    v6: "fe80::604:3"
    if:
      v4: "172.20.209.1"
      v6: "fe80::42:1"
    wg:
      port: "50604"
      endpoint: "de1.dn42.cas7.moe:20215"
      pubkey: "1dJpFLegKHKButkXqbv1KLLMTmS6KtFkWBz6GRo2uxE="
      privkey: "{{ lookup('passwordstore', 'infra/host/' + ansible_fqdn + '/dn42/moecast') }}"
    multiprotocol: yes
