---
- name: Add watchtower container
  docker_container:
    image: containrrr/watchtower
    name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --schedule "0 0 1 * * *"