---
- name: install nginx
  apt:
    pkg: ['nginx']
    state: present

- name: Create vhosts directory
  file:
    path: '/etc/nginx/vhosts'
    mode: 0755
    state: directory
    owner: root
    group: root

- name: Disable default site configuration
  file:
    dest: /etc/nginx/sites-enabled/default
    state: absent

- name: Install vhosts
  block:
    - template: src=vhosts/labcodede.labcode.party.j2 dest=/etc/nginx/vhosts/labcodede.labcode.party
      notify:
      - reload nginx
    - template: src=vhosts/bechillide.labcode.party.j2 dest=/etc/nginx/vhosts/bechillide.labcode.party
      notify:
      - reload nginx

- name: Install config
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify:
  - reload nginx