http:
  routers:
    iam-keycloak-http:
      rule: "Host(`auth.em0lar.de`) || Host(`auth.emolar.de`) || Host(`auth.labcode.de`) || Host(`keycloak.em0lar.de`) || Host(`keycloak.emolar.de`) || Host(`keycloak.labcode.de`)"
      service: "iam-keycloak@file"
      entryPoints:
        - "http"
      middlewares:
        - "https_redirect"
    iam-keycloak-https:
      rule: "Host(`auth.em0lar.de`) || Host(`auth.emolar.de`) || Host(`auth.labcode.de`) || Host(`keycloak.em0lar.de`) || Host(`keycloak.emolar.de`) || Host(`keycloak.labcode.de`)"
      service: "iam-keycloak@file"
      entryPoints:
        - "https"
      tls:
        certResolver: "le_tls"
      middlewares:
        - "hsts"
  services:
    iam-keycloak:
      loadBalancer:
        servers:
          - url: "http://{{ iam_hostname }}:8080"
