http:
  routers:
    internal_prometheus-http:
      rule: "Host(`dione.int.sig.de.labcode.de`) && Path(`/metrics/prometheus`)"
      service: "prometheus@internal"
      entryPoints:
        - "http"
      middlewares:
        - "https_redirect"
    internal_prometheus-https:
      rule: "Host(`dione.int.sig.de.labcode.de`) && Path(`/metrics/prometheus`)"
      service: "prometheus@internal"
      entryPoints:
        - "https"
      tls:
        certResolver: "le_tls"
