http:
  middlewares:
    removeAuthHeaders:
      headers:
        customRequestHeaders:
          X-Auth-Email: ""
          X-Auth-Audience: ""
          X-Auth-ExpiresIn: ""
          X-Auth-Groups: ""
          X-Auth-Roles: ""
          X-Auth-Subject: ""
          X-Auth-Token: ""
          X-Auth-UserID: ""
          X-Auth-Username: ""
