http:
  routers:
    nginx-static_labcode_de-http:
      rule: "Host(`static.labcode.de`) || Host(`cdn.labcode.de`)"
      service: "nginx@file"
      entryPoints:
        - "http"
      middlewares:
        - "https_redirect"
    nginx-static_labcode_de-https:
      rule: "Host(`static.labcode.de`) || Host(`cdn.labcode.de`)"
      service: "nginx@file"
      entryPoints:
        - "https"
      tls:
        certResolver: "le_tls"
      middlewares:
        - "hsts"
