http:
  routers:
    nginx-webhooks_titan_int_sig_de_labcode.de-http:
      rule: "Host(`webhooks.titan.int.sig.de.labcode.de`)"
      service: "nginx@file"
      entryPoints:
        - "http"
      middlewares:
        - "https_redirect"
    nginx-webhooks_titan_int_sig_de_labcode.de-https:
      rule: "Host(`webhooks.titan.int.sig.de.labcode.de`)"
      service: "nginx@file"
      entryPoints:
        - "https"
      tls:
        certResolver: "le_tls"
      middlewares:
        - "hsts"
        - "titan-webhooks-auth"
  middlewares:
    titan-webhooks-auth:
      basicAuth:
        users:
          - "webhooks:{{ lookup('passwordstore', 'infra/host/titan.int.sig.de.labcode.de/webhooks_basic_auth') | password_hash('bcrypt') }}"
