http:
  routers:
    nginx-labcode_de-http:
      rule: "Host(`labcode.de`) || Host(`www.labcode.de`)"
      service: "nginx@file"
      entryPoints:
        - "http"
      middlewares:
        - "https_redirect"
    nginx-labcode_de-https:
      rule: "Host(`labcode.de`) || Host(`www.labcode.de`)"
      service: "nginx@file"
      entryPoints:
        - "https"
      tls:
        certResolver: "le_tls"
      middlewares:
        - "hsts"
        - "www_redirect"
