http:
  routers:
    nginx-element_em0lar_de-http:
      rule: "Host(`element.em0lar.de`)"
      service: "nginx@file"
      entryPoints:
        - "http"
      middlewares:
        - "https_redirect"
    nginx-element_em0lar_de-https:
      rule: "Host(`element.em0lar.de`)"
      service: "nginx@file"
      entryPoints:
        - "https"
      tls:
        certResolver: "le_tls"
      middlewares:
        - "hsts"
