http:
  routers:
    services-git_labcode_dev-http:
      rule: "Host(`git.labcode.dev`) || Host(`git.em0lar.de`) || Host(`git.emolar.de`) || Host(`git.lbcd.dev`) || Host(`git.labcode.de`)"
      service: "services-gitea@file"
      entryPoints:
        - "http"
      middlewares:
        - "https_redirect"
    services-git_labcode_dev-https:
      rule: "Host(`git.labcode.dev`) || Host(`git.em0lar.de`) || Host(`git.emolar.de`) || Host(`git.lbcd.dev`) || Host(`git.labcode.de`)"
      service: "services-gitea@file"
      entryPoints:
        - "https"
      tls:
        certResolver: "le_tls"
      middlewares:
        - "hsts"
  services:
    services-gitea:
      loadBalancer:
        servers:
          - url: "http://{{ web_services_hostname }}:40000"

tcp:
  routers:
    services-git_labcode_dev-ssh:
      entryPoints:
        - "ssh_gitea"
      rule: "HostSNI(`*`)"
      service: "services-gitea-ssh@file"
  services:
    services-gitea-ssh:
      loadBalancer:
        servers:
        - address: "{{ web_services_hostname }}:222"
