http:
  routers:
    services-matrix_labcode_de-http:
      rule: "Host(`matrix.labcode.de`)"
      service: "services-matrix@file"
      entryPoints:
        - "http"
      middlewares:
        - "https_redirect"
    services-matrix_labcode_de-https:
      rule: "Host(`matrix.labcode.de`)"
      service: "services-matrix@file"
      entryPoints:
        - "https"
      tls:
        certResolver: "le_tls"
  services:
    services-matrix:
      loadBalancer:
        servers:
          - url: "http://{{ web_services_hostname }}:8008"