---
- name: reload network
  service:
    name: "network"
    state: reloaded

- name: reload firewall
  service:
    name: "firewall"
    state: reloaded

- name: restart dnsmasq
  service:
    name: "dnsmasq"
    state: restarted

- name: restart uhttpd
  service:
    name: "uhttpd"
    state: restarted

- name: restart prometheus-node-exporter-lua
  service:
    name: "prometheus-node-exporter-lua"
    state: restarted

- name: restart bind
  service:
    name: "named"
    state: restarted
