---
- name: Create PostgreSQL synapse user
  postgresql_user:
    name: "synapse"
    password: "{{ synapse_db_password }}"
    login_host: "{{ web_db_postgres_host }}"
    login_user: "web-admin"
    login_password: "{{ web_db_postgres_password }}"

- name: Create PostgreSQL synapse db
  postgresql_db:
    name: "synapse"
    owner: "synapse"
    encoding: "UTF-8"
    lc_collate: "C"
    lc_ctype: "C"
    template: "template0"
    login_host: "{{ web_db_postgres_host }}"
    login_user: "web-admin"
    login_password: "{{ web_db_postgres_password }}"

- name: Create synapse data directory
  file:
    path: "/opt/matrix-synapse/data/"
    state: directory
    owner: "synapse"
    group: "synapse"

- name: Install synapse pip package
  pip:
    name: "matrix-synapse==1.12.0"
    virtualenv: "/opt/matrix-synapse/.venv"
    virtualenv_command: "/usr/bin/python3 -m venv"
    state: present
  become_user: synapse

- name: Install psycopg2 pip package
  pip:
    name: "psycopg2"
    virtualenv: "/opt/matrix-synapse/.venv"
    virtualenv_command: "/usr/bin/python3 -m venv"
    state: present
  become_user: synapse

- name: Add systemd service file for matrix-synapse
  copy:
    src: "matrix-synapse.service"
    dest: "/etc/systemd/system/matrix-synapse.service"

- name: Ensure matrix-synapse systemd service is enabled and running
  systemd:
    name: "matrix-synapse"
    daemon_reload: yes
    enabled: yes
    state: started