---
firefly_iii_version: "5.4.0-beta.1"

firefly_iii_app_key: "{{ lookup('passwordstore', 'infra/service/firefly-iii/app_key') }}"
firefly_iii_database_type: "pgsql"
firefly_iii_database_host: "rhea.int.sig.de.labcode.de"
firefly_iii_database_port: "5432"
firefly_iii_database_database: "{{ lookup('passwordstore', 'infra/db/firefly-iii subkey=name') }}"
firefly_iii_database_username: "{{ lookup('passwordstore', 'infra/db/firefly-iii subkey=user') }}"
firefly_iii_database_password: "{{ lookup('passwordstore', 'infra/db/firefly-iii') }}"

firefly_iii_mail_host: "mail.labcode.de"
firefly_iii_mail_port: "465"
firefly_iii_mail_from: "no-reply@labcode.de"
firefly_iii_mail_user: "no-reply@labcode.de"
firefly_iii_mail_password: "{{ lookup('passwordstore', 'labcode/mails/no-reply@labcode.de') }}"
firefly_iii_mail_encryption: "ssl"

firefly_iii_authentication_guard: "remote_user_guard"
firefly_iii_authentication_guard_header: "HTTP_X_AUTH_USERNAME"
firefly_iii_base_path: "/var/www/em0lar.de/finances.em0lar.de"
firefly_iii_site_owner: "webmaster@labcode.de"
firefly_iii_trusted_proxies: "**"
firefly_iii_cookie_domain: "finances.em0lar.de"
firefly_iii_app_url: "https://finances.em0lar.de"


firefly_iii_spectre_importer_version: "1.0.5"

