---
- name: Create Jitsi config directory
  file:
    path: /opt/jitsi/config
    recurse: yes
    state: directory

- name: Clone docker-jitsi-meet git repository
  git:
    repo: 'https://github.com/jitsi/docker-jitsi-meet.git'
    dest: /opt/jitsi/repo

- name: Create jitsi configuration
  template:
    src: .env.j2
    dest: /opt/jitsi/repo/.env

- name: Pull and start jitsi docker containers
  docker_compose:
    project_src: "/opt/jitsi/repo"
    pull: yes
    project_name: "jitsi"
    state: present

- name: Set up jitsi jvb_auth user
  shell:
    cmd: "docker-compose -p jitsi exec -T prosody prosodyctl --config /config/prosody.cfg.lua register {{ item.0 }} meet.labcode.de {{ item.1 }}"
  args:
    chdir: /opt/jitsi/repo/
  loop:
    - ["jvb", "{{ jitsi.jvb_auth_password }}"]
    - ["focus", "{{ jitsi.jicofo_auth_password }}"]
    - ["admin", "{{ jitsi.admin_password }}"]
