---
- name: Make sure directories exist
  file:
    path: "{{ firefly_iii_base_path }}/spectre-importer"
    owner: "www-data"
    group: "www-data"
    mode: 0775
    state: directory

- name: Check if directory with version alrady exists
  stat:
    path: "{{ firefly_iii_base_path }}/spectre-importer/{{ firefly_iii_spectre_importer_version }}"
  register: stat_current_version_directory

- block:
  - name: Install Firefly III
    composer:
      command: create-project
      arguments: "firefly-iii/spectre-importer {{ firefly_iii_base_path }}/spectre-importer/{{ firefly_iii_spectre_importer_version }} {{ firefly_iii_spectre_importer_version }}"
      working_dir: "/var/www/em0lar.de/finances.em0lar.de"
      prefer_dist: yes
    become_user: "www-data"

  - name: Link current version installation directory
    file:
      src: "{{ firefly_iii_base_path }}/spectre-importer/firefly-iii-{{ firefly_iii_spectre_importer_version }}"
      dest: "{{ firefly_iii_base_path }}/spectre-importer/current"
      owner: "www-data"
      group: "www-data"
      state: link
    when: firefly_iii_link_current_version_directory
  when: not stat_current_version_directory.stat.exists

- name: Template environment file
  template:
    src: ".env.j2"
    dest: "{{ firefly_iii_base_path }}/spectre-importer/firefly-iii-{{ firefly_iii_spectre_importer_version }}/.env"
    owner: "www-data"
    group: "www-data"
