providers:
  docker:
    exposedByDefault: false
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

api:
  dashboard: true

entryPoints:
  http:
    address: ":80"

  https:
    address: ":443"

certificatesResolvers:
  le_tls:
    acme:
      tlsChallenge: {}
      email: webmaster@labcode.de
      storage: /letsencrypt/acme_tls.json

log:
  format: json
  level: INFO