---
- name: Create Bind-Zones directory
  file:
    path: "{{ powerdns_base_directory }}/bind/zones"
    mode: 0755
    owner: pdns
    group: pdns
    recurse: yes
    state: directory

- name: Upload named.conf
  template:
    src: "named.conf.j2"
    dest: "{{ powerdns_base_directory }}/bind/named.conf"
    mode: 0644
  notify: restart powerdns

- name: Copy zone files
  template:
    src: "{{ item }}"
    dest: "{{ powerdns_base_directory }}/bind/zones"
    owner: pdns
    group: pdns
    mode: 0755
  with_fileglob: "templates/zones/*"

- name: Check if Bind dnssec db already exists
  stat:
    path: "{{ powerdns_bind_dnssec_database_file }}"
  register: stat_dnssec_file

- name: Create Bind dnssec db
  command: "pdnsutil create-bind-db {{ powerdns_bind_dnssec_database_file }}"
  become: yes
  become_user: pdns
  when: not stat_dnssec_file.stat.exists

- include_tasks: import_tsig_keys.yml
  loop: "{{ pdns_bind_tsig_keys }}"

- include_tasks: activate_tsig_keys.yml
  loop: "{{ pdns_bind_domains_tsig }}"
