---
- name: Add/Modify DNS record for rhein-sieg.opendatamap.net
  cloudflare_dns:
    account_email: "{{ cloudflare_api_email }}"
    account_api_token: "{{ cloudflare_api_token }}"
    record: "rhein-sieg"
    value: "{{ ansible_fqdn }}"
    type: CNAME
    zone: "opendatamap.net"
    state: present

- name: Add traefik config for rhein-sieg.opendatamap.net
  copy:
    src: rhein-sieg_opendatamap_net.yml
    dest: /volume/docker/traefik/config/dynamic/rhein-sieg_opendatamap_net.yml