- name: remove certbot
  apt:
    pkg: ['certbot']
    update_cache: true
    state: absent

- name: remove certbot-dns-cloudflare
  pip:
    name: ['wheel', 'certbot-dns-cloudflare']
    executable: pip3
    state: absent

- name: Remove Cloudflare API key file
  file:
    path: "/etc/letsencrypt/dnscloudflare.ini"
    state: absent

- name: remove rule for Let's Encrypt API to v2
  file:
    path: /etc/letsencrypt/cli.ini
    state: absent

- name: Remove Cronjob doe renewing certificates every month
  cron:
    name: renew letsencrypt certs
    special_time: monthly
    job: "/usr/bin/env certbot renew --post-hook 'systemctl restart nginx'"
    user: root
    state: absent


- name: remove dhparam key by mozilla
  file:
    path: /etc/ssl/private/dhparam.pem
    state: absent