- name: Install certbot, python3 pip, python2/3 setuptools
  apt:
    pkg: ['certbot']
    update_cache: true
    state: present

- name: Install certbot-dns-cloudflare
  pip:
    name: ['wheel', 'certbot-dns-cloudflare']
    executable: pip3

- name: Create Cloudflare API key file
  copy:
    dest: "/etc/letsencrypt/dnscloudflare.ini"
    mode: 0600
    content: |
      dns_cloudflare_api_key = {{ cloudflare_api_key }}
      dns_cloudflare_email = {{ cloudflare_email }}

- name: Change Let's Encrypt API to v2
  lineinfile:
    path: /etc/letsencrypt/cli.ini
    line: 'server = https://acme-staging-v02.api.letsencrypt.org/directory'

- name: Generate Certificate for Domains
  shell: certbot certonly -d *.labcode.party -d labcode.party --dns-cloudflare --agree-tos --email webmaster@labcode.de -n --dns-cloudflare-credentials /etc/letsencrypt/dnscloudflare.ini
  notify: reload nginx


- name: remove certbot standard cronjob
  file:
    path: /etc/cron.d/certbot
    state: absent

- name: Add Cronjob doe renewing certificates every month
  cron:
    name: renew letsencrypt certs
    special_time: monthly
    job: "/usr/bin/env certbot renew --post-hook 'systemctl restart nginx'"
    user: root