---
- hosts: all,!backuponly,!openwrt,!notbase
  roles:
    - n0emis.base
    - jnv.unattended-upgrades
    - gantsign.oh-my-zsh
  handlers:
    - name: restart systemd-journald
      systemd:
        name: systemd-journald.service
        state: restarted
  tasks:
    - name: create certificate-transfer user
      user:
        name: "certificate-transfer"
        shell: "/bin/bash"
        state: present
      when: certificate_transfer_user_enable

    - name: add authorized key of certificate-transfer user
      authorized_key:
        user: "certificate-transfer"
        manage_dir: yes
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOs9IzvFrr/sg4K/Vtr6eZ9RrkWx2ybO5JzSwg6dRzVQ certificate-transfer"
        state: present
        exclusive: yes
      when: certificate_transfer_user_enable

    - name: Change SystemMaxUse in systemd-journald
      replace:
        path: "/etc/systemd/journald.conf"
        regexp: "^#SystemMaxUse="
        replace: "SystemMaxUse=50M"
      notify: restart systemd-journald

    - name: Remove uname in motd
      file:
        path: "/etc/update-motd.d/10-uname"
        state: absent

    - name: Use neofetch as motd"
      copy:
        content: |
          #!/bin/sh
          neofetch
        dest: "/etc/update-motd.d/10-neofetch"
        mode: "+x"

    - name: "Remove content of default motd"
      copy:
        content: ""
        dest: "/etc/motd"
