---
- hosts: dn42
  roles:
    - n0emis.dn42
  handlers:
    - name: save iptables
      shell: iptables-save > /etc/iptables/rules.v4

    - name: save ip6tables
      shell: ip6tables-save > /etc/iptables/rules.v6
  tasks:
    - name: Install iptables-persistent
      apt:
        name: "iptables-persistent"
        state: present

    - name: Reject ipv4 packets from dn42 to private wireguard
      iptables:
        ip_version: ipv4
        chain: FORWARD
        in_interface: "dn42_+"
        destination: "10.151.0.0/16"
        jump: REJECT
      notify: save iptables

    - name: Reject ipv6 packets from dn42 to private wireguard
      iptables:
        ip_version: ipv6
        chain: FORWARD
        in_interface: "dn42_+"
        destination: "fd8f:d15b:9f40::/48"
        jump: REJECT
      notify: save ip6tables
