---
- name: DNS Server
  hosts: dns
  roles:
    - powerdns-bind-backend
    - powerdns.pdns
    - n0emis.pdns_secondary
  tasks:
    - name: "Check if TSIG key '{{ powerdns_dynamicdns_remote_tsig_key_name }}' exists"
      command: "sqlite3 {{ powerdns_dynamicdns_database_file }} \"SELECT * FROM tsigkeys where name='{{ powerdns_dynamicdns_remote_tsig_key_name }}' AND algorithm='{{ powerdns_dynamicdns_remote_tsig_key_algorithm }}';\""
      register: sqlite3_tsigkey_check_command
      changed_when: false
      when: powerdns_dynamicdns_remote_tsig_key_name is defined

    - name: "Import TSIG key '{{ powerdns_dynamicdns_remote_tsig_key_name }}'"
      command: "sqlite3 {{ powerdns_dynamicdns_database_file }} \"INSERT INTO tsigkeys (name, algorithm, secret) values ('{{ powerdns_dynamicdns_remote_tsig_key_name }}', '{{ powerdns_dynamicdns_remote_tsig_key_algorithm }}', '{{ powerdns_dynamicdns_remote_tsig_key_secret }}');\""
      when: sqlite3_tsigkey_check_command.stdout | length == 0
      notify: restart powerdns
