---
- hosts: web_database
  tags: web_database
  roles:
    - geerlingguy.postgresql
    - undergreen.mongodb

- hosts: matrix
  tags: matrix
  roles:
    - n0emis.synapse
    - mautrix-telegram

- hosts: gitea
  tags: gitea
  roles:
    - thomas-maurice.gitea

- hosts: hedgedoc
  roles:
    - geerlingguy.nodejs
    - ocha.yarn
    - em0lar.hedgedoc
  tasks:
    - name: Upload saml cert
      copy:
        dest: "{{ hedgedoc_base_path + '/idp_cert.pem' }}"
        content: "{{ hedgedoc_saml_idp_cert }}"
    - name: Upload saml private key
      copy:
        src: "../../files/hedgedoc/idp_key.pem"
        dest: "{{ hedgedoc_base_path + '/idp_key.pem' }}"
  tags: hedgedoc

- hosts: web_caddy
  tags: web_caddy_content
  pre_tasks:
    - name: download GPG Key from php repository (sury)
      apt_key:
        url: "https://packages.sury.org/php/apt.gpg"
        state: present

    - name: enable php repository (sury)
      apt_repository:
        repo: "deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main"
        state: present
  roles:
          #    - geerlingguy.php
          #    - powerdns-dynamicdns
    - nextcloud
    - element-web
  tasks:
    - name: Create directories and apply correct permissions to them
      file:
        path: "/var/www/{{ item }}"
        owner: "caddy"
        group: "caddy"
        recurse: yes
        state: directory
      loop:
        - "em0lar.de/em0lar.de"
        - "labcode.de/labcode.de"
        - "labcode.de/webhooks.titan.int.sig.de.labcode.de"
        - "labcode.de/webmail.labcode.de"

    - name: download static.labcode.de from Gitea
      git:
        repo: "https://git.em0lar.dev/em0lar/static.labcode.de.git"
        dest: "/var/www/labcode.de/static.labcode.de"

    - name: Add update.php for webhooks.titan
      template:
        src: files/webhooks.titan.int.sig.de.labcode.de/update.php.j2
        dest: "/var/www/labcode.de/webhooks.titan.int.sig.de.labcode.de/update.php"

    - name: download ask.e1mo.de repo from GitHub
      git:
        repo: "https://github.com/e1mo/ask.e1mo.de.git"
        dest: "/var/www/em0lar.de/tell.em0lar.de"
        version: "v2.0.3"
    - name: Template config for tell.em0lar.de
      template:
        src: "files/tell.em0lar.de/config.php.j2"
        dest: "/var/www/em0lar.de/tell.em0lar.de/config.php"

    - name: extract rainloop release archive
      unarchive:
        src: "https://github.com/RainLoop/rainloop-webmail/releases/download/v{{ rainloop_version }}/rainloop-community-{{ rainloop_version }}.zip"
        remote_src: yes
        dest: "/var/www/labcode.de/webmail.labcode.de"
        owner: "caddy"
        group: "caddy"

- hosts: web_caddy
  tags: web_caddy
  roles:
    - em0lar.caddy
