---
- hosts: wireguard_member
  tags: wireguard
  roles:
    - adamruzicka.wireguard
  tasks:
    - name: Create wireguard_peer config for main wireguard server
      set_fact:
        wireguard_peer:
          public_key: "{{ wireguard_server_public_key }}"
          allowed_ips: "{{ wireguard_server_address }}"

- hosts: wireguard
  tags: wireguard
  pre_tasks:
    - name: Create wireguard peers config with host items
      set_fact:
        wireguard_wg_server_peers: "{{ wireguard_wg_server_peers | combine({ 'server_' + hostvars[item].ansible_facts.fqdn: hostvars[item].wireguard_peer }) }}"
      when: "hostvars[item].ansible_facts.fqdn is defined and hostvars[item].ansible_facts.fqdn != ansible_fqdn"
      with_items: "{{ groups['wireguard_member'] }}"
  roles:
    - adamruzicka.wireguard
