router_static_hosts:
  - name: coreswitch
    v4: 10.151.0.4
    mac: a4:2b:8c:12:5b:96

  - name: ap-openwrt-1
    v4: 10.151.0.128
    mac: 14:59:c0:c7:02:b9

  - name: ap-unifi-1
    v4: 10.151.0.129
    mac: 80:2a:a8:93:df:57

  - name: fritz
    v4: 10.151.0.130
    mac: c0:25:06:5f:df:ae

  - name: ap-openwrt-2
    v4: 10.151.0.131
    mac: b0:4e:26:a8:42:38

  - name: hue
    v4: 10.151.1.2
    mac: 00:17:88:21:71:71

  - name: sonos-kueche-l
    v4: 10.151.1.64
    mac: 00:0e:58:54:e3:54

  - name: sonos-kueche-r
    v4: 10.151.1.65
    mac: 00:0e:58:54:e3:60

  - name: sonos-muck
    v4: 10.151.1.66
    mac: 00:0e:58:5e:b5:9a

  - name: sonos-em0lar
    v4: 10.151.1.67
    mac: 00:0e:58:cd:70:3c

  - name: sonos-em0lar-attic
    v4: 10.151.1.68
    mac: 94:9f:3e:19:c1:62

  - name: sonos-wohnzimmer
    v4: 10.151.1.69
    mac: 94:9f:3e:6a:85:e5

  - name: sonos-wohnzimmer-sl
    v4: 10.151.1.70
    mac: 78:28:ca:e9:7d:0e

  - name: sonos-wohnzimmer-sr
    v4: 10.151.1.71
    mac: 78:28:ca:e9:37:ca

  - name: phoebe
    v4: 10.151.4.11
    mac: aa:53:96:a0:ee:47

  - name: paul-ext
    v4: 10.151.4.14
    mac: c6:a0:97:d3:86:00

  - name: tethys
    v4: 10.151.4.1
    hostid: 2
    mac: 3c:d9:cc:ad:6e:31

  - name: encladus
    v4: 10.151.5.1
    hostid: 2
    mac: 00:11:32:69:05:05
