---
router_port_redirect:
  - name: "dione http"
    port: "80"
    src_network: "wan"
    dest_network: "lantethys"
    ip: "10.151.4.3"
    reflection_nets:
      - lan
  - name: "dione https"
    port: "443"
    src_network: "wan"
    network: "lantethys"
    ip: "10.151.4.3"
    reflection_nets:
      - lan
  - name: "dione gitea ssh"
    port: "222"
    src_network: "wan"
    network: "lantethys"
    ip: "10.151.4.3"
    reflection_nets:
      - lan

  - name: "helene ssh"
    port: "1880"
    src_network: "wan"
    network: "lantethys"
    ip: "10.151.4.13"
    reflection_src_external: yes
    reflection_nets:
      - lan

router_port_allow_ipv6:
  - name: "dione http ipv6"
    port: "80"
    src_network: "wan"
    network: "lantethys"
    ip: "2001:470:7285:2:3890:17ff:fe54:50de"
  - name: "dione https ipv6"
    port: "443"
    src_network: "wan"
    network: "lantethys"
    ip: "2001:470:7285:2:3890:17ff:fe54:50de"
  - name: "dione gitea ssh ipv6"
    port: "222"
    src_network: "wan"
    network: "lantethys"
    ip: "2001:470:7285:2:3890:17ff:fe54:50de"

  - name: "helene ssh ipv6"
    port: "1880"
    src_network: "wan"
    network: "lantethys"
    ip: "2001:470:7285:2:9cf1:ccff:fead:6e31"


router_firewall_forwarding:
  - lan
  - lantethys
  - lanencladus
  - wgserver
  - wgfdg
