---
router_port_redirect:
  - name: "helene ssh"
    port: "1880"
    src_network: "wan"
    network: "lantethys"
    ip: "10.151.4.13"
    reflection_src_external: yes
    reflection_nets:
      - lan

router_port_allow_ipv6: []

router_firewall_forwarding:
  - lan
  - lantethys
  - lanencladus
  - wgserver
  - wgfdg
