---
- name: Add/Modify DNS record for md.leomaroni.de
  cloudflare_dns:
    account_email: "{{ cloudflare_api_email }}"
    account_api_token: "{{ cloudflare_api_token }}"
    record: "md"
    value: "{{ ansible_fqdn }}"
    type: CNAME
    zone: "leomaroni.de"
    state: present

- name: Create /volume/docker/leomaroni.de/md.leomaroni.de directory
  file:
    path: '/volume/docker/leomaroni.de/md.leomaroni.de'
    state: directory
    recurse: yes

- name: Create/Launch docker container md.leomaroni.de-db
  docker_container:
    image: postgres:11
    name: md.leomaroni.de-db
    restart_policy: always
    env:
      POSTGRES_PASSWORD: "{{ codimd_db_password }}"
      POSTGRES_USER: "codimd"
      POSTGRES_DB: "codimd"
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - /volume/docker/leomaroni.de/md.leomaroni.de/db-data:/var/lib/mysql
      - ./resources/utf8.cnf:/etc/mysql/conf.d/utf8.cnf

- name: Create/launch docker container md.leomaroni.de-app
  docker_container:
    image: quay.io/codimd/server:1.6.0
    name: md.leomaroni.de-app
    restart_policy: always
    links:
      - md.leomaroni.de-db:db
    env:
      CMD_DB_URL: "postgres://codimd:{{ codimd_db_password }}@db:5432/codimd"
      CMD_ALLOW_FREEURL: "true"
      CMD_DOMAIN: "md.leomaroni.de"
      CMD_PROTOCOL_USESSL: "true"
      CMD_USECDN: "false"
      CMD_URL_ADDPORT: "false"
    labels:
      traefik.enable: "true"
      traefik.http.routers.md-leomaroni-de_http.rule: "Host(`md.leomaroni.de`)"
      traefik.http.routers.md-leomaroni-de_http.entryPoints: "http"
      traefik.http.routers.md-leomaroni-de_http.middlewares: "https_redirect@file"
      traefik.http.routers.md-leomaroni-de_https.rule: "Host(`md.leomaroni.de`)"
      traefik.http.routers.md-leomaroni-de_https.entryPoints: "https"
      traefik.http.routers.md-leomaroni-de_https.tls.certresolver: "le_http"

- name: Import md.leomaroni.de backup
  include_tasks: backup.yml