- name: Install default set up packages
  opkg:
    name: "{{ item }}"
    state: present
  loop:
    - vim
    - nmap
    - bind-dig
    - wireguard
    - luci
    - luci-proto-wireguard
    - luci-proto-ipv6
    - 6in4
    - tcpdump
    - rsync
    - curl
    - ip-full
    - python3
  tags: packages


- import_tasks: ohmyzsh.yml
  tags: packages

- import_tasks: config.yml
  tags: config

- import_tasks: ip6neigh.yml
  tags: ip6neigh

- name: Create cronjob for restarting PPPoE
  cron:
    name: "restart pppoe"
    hour: "04"
    minute: "30"
    user: "root"
    job: "ifup wan > /dev/null"
