---
- name: copy ssh-key
  copy:
    src: "ssh_key"
    dest: "{{ traefik_base_path }}/certificate-exporter-ssh-key"
    owner: "root"
    group: "root"
    mode: "0400"

- name: copy certificate export script
  template:
    dest: "{{ traefik_base_path }}/dumpcerts.sh"
    src: "dumpcerts.sh"
    owner: "root"
    group: "root"
    mode: 0744

- name: Install jq
  apt:
    name: "jq"

- name: setup traefik certificate-exporter cronjob
  cron:
    name: "traefik certificate-exporter"
    hour: "2"
    minute: "0"
    user: "root"
    job: "{{ traefik_base_path }}/dumpcerts.sh {{ traefik_base_path }}/acme_tls.json /etc/ssl/ > /dev/null"

- name: run traefik certificate-exporter
  command: '{{ traefik_base_path }}/dumpcerts.sh {{ traefik_base_path }}/acme_tls.json /etc/ssl/'