---
- name: Get hostname of web-standalone-server
  set_fact:
    web_standalone_hostname: "{{ item }}"
  when: hostvars[item].host.hoster == host.hoster
  with_items: "{{ groups.web_standalone_services }}"

- name: Add dynamic traefik configs to server
  template:
    dest: "/opt/traefik/config/dynamic/{{ item.path }}"
    src: "{{ item.path }}"
    owner: traefik
    group: traefik
  with_filetree: 'templates/'

- name: Add/Modify CNAME DNS records
  cloudflare_dns:
    account_email: "{{ cloudflare_api_email }}"
    account_api_token: "{{ cloudflare_api_token }}"
    record: "{{ item }}"
    value: "{{ ansible_fqdn }}"
    type: CNAME
    zone: "{{ item.split('.')[-2] }}.{{ item.split('.')[-1] }}"
    state: present
  with_items:
    - "grafana.opendatamap.net"
    - "kanban.opendatamap.net"
    - "node-red.opendatamap.net"
    - "rhein-sieg.opendatamap.net"
    - "bechilli.de"
    - "www.bechilli.de"
    - "cdn.labcode.de"
    - "cloud.leomaroni.de"
    - "docs.opendatamap.net"
    - "labcode.de"
    - "www.labcode.de"
    - "matrix.labcode.de"
    - "opendatamap.net"
    - "www.opendatamap.net"