http:
  routers:
    git_labcode_dev_http:
      rule: "Host(`git.labcode.dev`) || Host(`git.lbcd.dev`) || Host(`git.labcode.de`)"
      service: "services_gitea@file"
      entryPoints:
        - "http"
      middlewares:
        - "https_redirect"
    git_labcode_dev_https:
      rule: "Host(`git.labcode.dev`) || Host(`git.lbcd.dev`) || Host(`git.labcode.de`)"
      service: "services_gitea@file"
      entryPoints:
        - "https"
      tls:
        certResolver: "le_tls"
  services:
    services_gitea:
      loadBalancer:
        servers:
          - url: "http://{{ web_services_hostname }}:40000"

tcp:
  routers:
    git_labcode_dev_ssh:
      entryPoints:
        - "ssh_gitea"
      rule: "HostSNI(`*`)"
      service: "services_gitea_ssh@file"
  services:
    services_gitea_ssh:
      loadBalancer:
        servers:
        - address: "{{ web_services_hostname }}:222"