---
- name: Create /docker/labcode.dev/bsvrs-web.labcode.dev directory
  file:
    path: '/docker/labcode.dev/bsvrs-web.labcode.dev'
    state: directory
    recurse: yes

- name: Create/Launch docker container bsvrs-web.labcode.dev-db
  docker_container:
    image: mariadb:10
    name: bsvrs-web.labcode.dev-db
    restart_policy: always
    volumes:
      - /docker/labcode.dev/bsvrs-web.labcode.dev/db-data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    env:
      MYSQL_ROOT_PASSWORD: "{{ wordpress_db_root_password }}"
      MYSQL_PASSWORD: "{{ wordpress_db_password }}"
      MYSQL_DATABASE: "{{ wordpress_db_database }}"
      MYSQL_USER: "{{ wordpress_db_user }}"

- name: Create/launch docker container bsvrs-web.labcode.dev-app
  docker_container:
    image: wordpress:php7.3-apache
    name: bsvrs-web.labcode.dev-app
    links:
      - bsvrs-web.labcode.dev-db:db
    ports:
      - 127.0.0.1:40005:80
    restart_policy: always
    volumes:
      - /docker/labcode.dev/bsvrs-web.labcode.dev/html:/var/www/html
    env:
      WORDPRESS_DB_HOST: "db"
      WORDPRESS_DB_USER: "{{ wordpress_db_user }}"
      WORDPRESS_DB_NAME: "{{ wordpress_db_database }}"
      WORDPRESS_DB_PASSWORD: "{{ wordpress_db_password }}"