---
- name: download opendatamap.net from GitHub
  git:
    repo: "https://github.com/OpenDataMap/opendatamap.net.git"
    dest: "/var/www/opendatamap.net/opendatamap.net"
    force: yes

# TODO: Build OpenDataMap

- name: Add nginx config for opendatamap.net
  copy:
    src: "nginx_vhost.conf"
    dest: "/etc/nginx/vhosts/opendatamap_net.conf"
  notify:
    - reload nginx