---
- name: download opendatamap.net from GitHub
  git:
    repo: 'https://github.com/OpenDataMap/opendatamap.net.git'
    dest: /var/www/opendatamap.net/opendatamap.net
    force: yes

- name: Change opendatamap.net ownership
  file:
    path: /var/www/opendatamap.net/opendatamap.net
    owner: leo
    group: users
    recurse: yes

- name: build jekyll
  docker_container:
    image: jekyll/builder:3.8.5
    name: opendatamap.net-builder
    volumes:
      - /var/www/opendatamap.net/opendatamap.net:/srv/jekyll
    command: jekyll build
    env:
      JEKYLL_UID: "1001"
      JEKYLL_GID: "1001"

- name: Create/launch docker container opendatamap.net-web
  docker_container:
    image: nginx:latest
    name: opendatamap.net-web
    restart_policy: always
    volumes:
      - /var/www/opendatamap.net/opendatamap.net/_site:/usr/share/nginx/html
    labels:
      traefik.enable: "true"
      traefik.http.routers.opendatamap-net_http.rule: "Host(`opendatamap.net`)"
      traefik.http.routers.opendatamap-net_http.entryPoints: "http"
      traefik.http.routers.opendatamap-net_http.middlewares: "https_redirect@file"
      traefik.http.routers.opendatamap-net_https.rule: "Host(`opendatamap.net`)"
      traefik.http.routers.opendatamap-net_https.entryPoints: "https"
      traefik.http.routers.opendatamap-net_https.tls.certresolver: "le_tls"