---
- hosts: all
  gather_facts: yes

- import_playbook: include/base.yml
  tags: base

- import_playbook: include/dns.yml
  tags: dns

- import_playbook: include/wireguard.yml
  tags: dns

- import_playbook: include/mail.yml
  tags: mail

- import_playbook: include/iam.yml

- import_playbook: include/videoconferencing.yml

- import_playbook: include/dn42.yml
  tags: dn42

- import_playbook: include/backup.yml

- hosts: monitored
  become: yes
  roles:
    - fahrplandatengarten.icinga
  tags: icinga,monitoring
