---
# file: site.yml
- hosts: all
  roles:
#    - lbcd.packages
    - general.users
    - general.authentication
    - general.packages
    - general.unattended-upgrades
- name: web
  import_playbook: web.yaml