---
- hosts: all
  tags: base
  roles:
    - n0emis.base
    - jnv.unattended-upgrades
    - oh-my-zsh
  tasks:
    - name: create ci user
      user:
        name: "ci"
        shell: "/bin/bash"
        state: present
      when: ci_user_enable

    - name: add authorized key of ci user
      authorized_key:
        user: "ci"
        manage_dir: yes
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGfB6HQy8CnGNlcZn1cpM25eZPTXNnYePeyQlSogieo8 droneci"
        state: present
        exclusive: yes
      when: ci_user_enable

# Web

- hosts: web_database
  tags: web,web_database
  roles:
    - postgresql
    - undergreen.mongodb

- hosts: web_services
  tags: web,web_services
  roles:
    - gitea
    - matrix
    - geerlingguy.nodejs
    - codimd
    - wekan

- hosts: web_nginx
  tags: web,web_nginx
  roles:
    - php-fastcgi
    - nginx
    - nextcloud
    - static.labcode.de
    - labcode.de
    - docs.opendatamap.net
    - bechilli.de
    - matrix-well-known

- hosts: web_reverseproxy
  tags: web,web_reverseproxy
  roles:
    - dynamicdns
    - traefik
    - traefik-services

# CI

- name: drone_ci
  tags: drone_ci
  hosts: drone_ci
  roles:
    - docker
    - drone-ci

# Mail

- name: mail
  tags: mail
  hosts: mail
  roles:
    - docker
    - mail/hcloud-volume
    - mail/mailcow

# DNS
- name: DNS Server
  hosts: dns
  tags: dns
  vars:
    coredns_config_file: files/coredns/Corefile.j2
  roles:
    - cloudalchemy.coredns

# Pihole

- name: pihole
  tags: pihole
  hosts: pihole
  roles:
    - pihole

# Jitsi

- name: jitsi
  tags: jitsi
  hosts: jitsi
  roles:
    - docker
    - docker-traefik-reverseproxy
    - jitsi