---
- hosts: all
  tags: base
  roles:
    - base-dns
    - base
    - oh-my-zsh

- name: web
  tags: web
  import_playbook: web.yml

- name: drone_ci
  tags: drone_ci
  hosts: drone_ci
  roles:
    - docker
    - drone-ci

- name: mail
  tags: mail
  import_playbook: mail.yml

- name: pihole
  tags: pihole
  hosts: pihole
  roles:
    - pihole

- name: jitsi
  tags: jitsi
  import_playbook: jitsi.yml