---
# file: site.yml
- hosts: all
  tags: base
  roles:
    - base
    - openvpn

- name: web
  tags: web
  import_playbook: web.yml

- name: mail
  tags: mail
  import_playbook: mail.yml

- name: pihole
  tags: pihole
  import_playbook: pihole.yml