- hosts: web_database
  roles:
    - postgresql

- hosts: web_services
  roles:
    - gitea
    - matrix

- hosts: web_nginx
  roles:
    - php-fastcgi
    - nginx
    - nextcloud
    - static.labcode.de
    - labcode.de
    - docs.opendatamap.net
    - bechilli.de
    - matrix-well-known

- hosts: web_reverseproxy
  tags: web_reverseproxy
  roles:
    - traefik
    - traefik-services
