---
- name: Create /volume/docker/leomaroni.de/cloud.leomaroni.de directory
  file:
    path: '/volume/docker/leomaroni.de/cloud.leomaroni.de'
    state: directory
    recurse: yes

- name: Create/Launch docker container cloud.leomaroni.de-mariadb
  docker_container:
    image: mariadb:10
    name: cloud.leomaroni.de-db
    restart_policy: always
    volumes:
      - /volume/docker/leomaroni.de/cloud.leomaroni.de/db-data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    env:
      MYSQL_ROOT_PASSWORD: "{{ nextcloud_db_root_password }}"
      MYSQL_PASSWORD: "{{ nextcloud_db_password }}"
      MYSQL_DATABASE: "{{ nextcloud_db_database }}"
      MYSQL_USER: "{{ nextcloud_db_user }}"

- name: Create/launch docker container cloud.leomaroni.de-app
  docker_container:
    image: nextcloud:18
    name: cloud.leomaroni.de-app
    restart_policy: always
    links:
      - cloud.leomaroni.de-db:db
    volumes:
      - /volume/docker/leomaroni.de/cloud.leomaroni.de/config:/var/www/html/config
      - /volume/docker/leomaroni.de/cloud.leomaroni.de/custom_apps:/var/www/html/custom_apps
      - /volume/docker/leomaroni.de/cloud.leomaroni.de/data:/var/www/html/data
      - /volume/docker/leomaroni.de/cloud.leomaroni.de/themes:/var/www/html/themes
      - /etc/localtime:/etc/localtime:ro
    ports:
      127.0.0.1:40001:80
    env:
      MYSQL_HOST: "db"
      MYSQL_USER: "{{ nextcloud_db_user }}"
      MYSQL_DATABASE: "{{ nextcloud_db_database }}"
      MYSQL_PASSWORD: "{{ nextcloud_db_password }}"
      NEXTCLOUD_ADMIN_USER: "{{ nextcloud_admin_user }}"
      NEXTCLOUD_ADMIN_PASSWORD: "{{ nextcloud_admin_password }}"
    labels:
      traefik.enable: "true"
      traefik.http.routers.cloud-leomaroni-de_http.rule: "Host(`cloud.leomaroni.de`)"
      traefik.http.routers.cloud-leomaroni-de_http.entryPoints: "http"
      traefik.http.routers.cloud-leomaroni-de_http.middlewares: "https_redirect@file"
      traefik.http.routers.cloud-leomaroni-de_https.rule: "Host(`cloud.leomaroni.de`)"
      traefik.http.routers.cloud-leomaroni-de_https.entryPoints: "https"
      traefik.http.routers.cloud-leomaroni-de_https.tls.certresolver: "le_tls"