---
synapse_pip_version: "1.23.0"

synapse_domain: "labcode.de"
synapse_server_fqdn_matrix: "matrix.{{ synapse_domain }}"
synapse_http_listener_port: 8008
synapse_additional_listeners: |
  # Unsecure HTTP listener (Client API): for when matrix traffic passes through a reverse proxy
  # that unwraps TLS.
  - port: {{ synapse_http_listener_port }}
    tls: false
    type: http
    x_forwarded: true
    resources:
      - names: [client,federation,metrics]
        compress: false
synapse_http_listener_enabled: false
synapse_federation_listener_enabled: false
synapse_metrics_enabled: true

synapse_database_host: "rhea.int.sig.de.labcode.de"
synapse_database_user: "{{ lookup('passwordstore', 'infra/db/synapse subkey=user') }}"
synapse_database_password: "{{ lookup('passwordstore', 'infra/db/synapse') }}"
synapse_database_database: "synapse"

synapse_registration_shared_secret: "{{ lookup('passwordstore', 'infra/service/matrix/synapse/shared_secret') }}"
synapse_macaroon_secret_key: "{{ lookup('passwordstore', 'infra/service/matrix/synapse/macaroon_secret') }}"
synapse_form_secret: "{{ lookup('passwordstore', 'infra/service/matrix/synapse/form_secret') }}"
synapse_signing_key: "{{ lookup('passwordstore', 'infra/service/matrix/synapse/signing_key') }}"
synapse_password_config_pepper: "{{ lookup('passwordstore', 'infra/service/matrix/synapse/password_pepper') }}"


synapse_turn_uris:
  - "turn:turn.labcode.de:3479?transport=udp"
  - "turn:turn.labcode.de:3479?transport=tcp"
synapse_turn_shared_secret: "{{ lookup('passwordstore', 'infra/host/meet01.het.nue.de.labcode.de/coturn') }}"
synapse_turn_allow_guests: True

synapse_app_service_config_files:
  - "{{ mautrix_telegram_config_path }}/registration.yaml"

synapse_url_preview_enabled: false
synapse_allow_public_rooms_over_federation: true

synapse_homeserver_config_extra_options: |
  federation_metrics_domains:
    - matrix.org
    - chaos.jetzt
    - noemis.me
