---
openldap_debian_packages:
  - slapd
  - ldap-utils
openldap_admin_password: "{{ lookup('passwordstore', 'infra/service/ldap/admin') }}"
openldap_org: "labcode"
openldap_tld: "de"

openldap_config: true
openldap_populate: true
openldap_posixgroups: []
openldap_users: []
openldap_organizationalunits:
  - People
  - Groups
  - Roles

