- name: download GPG Key from php repository (sury)
  apt_key:
    url: "https://packages.sury.org/php/apt.gpg"
    state: present

- name: enable php repository (sury)
  apt_repository:
    repo: "deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main"
    state: present

- name: install php 7.3 fpm
  apt:
    pkg:
      - "php7.4-fpm"
      - "php7.4-pgsql"
    state: present