- name: Create traefik config directory
  file:
    path: "/volume/docker/traefik/config"
    state: directory

- name: Add traefik static config to host
  copy:
    dest: "/volume/docker/traefik/config/traefik.yml"
    src: "static.yml"

- name: Create traefik dynamic config directory
  file:
    path: "/volume/docker/traefik/config/dynamic"
    state: directory

- name: Add traefik middlewares config to host
  copy:
    dest: "/volume/docker/traefik/config/dynamic/middlewares.yml"
    src: "middlewares.yml"

- name: Add traefik tls config to host
  copy:
    dest: "/volume/docker/traefik/config/dynamic/tls.yml"
    src: "tls.yml"

- name: Add traefik dashboard config to host
  template:
    dest: "/volume/docker/traefik/config/dynamic/dashboard.yml"
    src: "dashboard.yml"

- name: Run Traefik Docker container
  docker_container:
    name: traefik
    image: traefik:2.1.2
    command: --providers.docker
    restart_policy: always
    ports:
      - "80:80"
      - "443:443"
      - "127.0.0.1:8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /volume/docker/traefik/config:/etc/traefik/
      - /volume/docker/traefik/letsencrypt:/letsencrypt