---
- name: Add/Modify DNS record for node-red.opendatamap.net
  cloudflare_dns:
    account_email: "{{ cloudflare_api_email }}"
    account_api_token: "{{ cloudflare_api_token }}"
    record: "node-red"
    value: "{{ ansible_fqdn }}"
    type: CNAME
    zone: "opendatamap.net"
    state: present

- name: Add traefik config for node-red.opendatamap.net
  copy:
    src: node-red_opendatamap_net.yml
    dest: /volume/docker/traefik/config/dynamic/node_red_opendatamap_net.yml