---
- name: default deny everything
  ufw:
    default: deny

- name: allow www
  ufw:
    rule: allow
    name: WWW Full

- name: allow gitea's ssh
  ufw:
    rule: allow
    port: "22"

- name: enable ufw
  ufw:
    state: enabled