---
- name: Install OpenVPN
  apt:
    pkg: openvpn
    state: present
  when: host.hoster != "home"

- name: Create OpenVPN configuration
  copy:
    src: home.conf
    dest: /etc/openvpn/home.conf
    mode: 0400
  when: host.hoster != "home"

- name: Create OpenVPN keys directory
  file:
    path: /etc/openvpn/keys/
    state: directory
  when: host.hoster != "home"

- name: Add OpenVPN password file
  copy:
    src: home_authentication.txt
    dest: /etc/openvpn/keys/home_authentication.txt
    mode: 0400
  when: host.hoster != "home"

- name: Add OpenVPN CA file
  copy:
    src: home_ca.pem
    dest: /etc/openvpn/keys/home_ca.pem
    mode: 0400
  when: host.hoster != "home"

- name: Enable OpenVPN service
  service:
    name: openvpn@home
    enabled: yes
    state: started
  when: host.hoster != "home"