---
- name: Set fact for local ipv6 address of {{ host }}
  set_fact:
    local_ipv6_address: "{{ item }}"
  when: item.startswith("fd")
  loop: "{{ hostvars[host].ansible_all_ipv6_addresses }}"

- name: Add IPv4 address of {{ host }} to custom list
  lineinfile:
    dest: /etc/pihole/custom.list
    regexp: '.*{{ hostvars[host].ansible_default_ipv4.address }}$'
    line: "{{ hostvars[host].ansible_default_ipv4.address }} {{ hostvars[host].inventory_hostname }}"
    state: present

- name: Add local IPv6 address of {{ host }} to custom list
  lineinfile:
    dest: /etc/pihole/custom.list
    regexp: '.*{{ local_ipv6_address }}$'
    line: "{{ local_ipv6_address }} {{ hostvars[host].inventory_hostname }}"
    state: present