---

- name: Create pihole directory
  file:
    path: "/etc/pihole"
    state: directory

- stat:
    path: "/usr/local/bin/pihole"
  register: pihole_binary

- set_fact:
    pihole_installed: "{{ pihole_binary.stat.exists | default(false) }}"

- name: Copy pihole setup conf
  template:
    src: "setupVars.conf"
    dest: "/etc/pihole/setupVars.conf"

- name: Download pihole install script
  get_url:
    url: "https://raw.githubusercontent.com/pi-hole/pi-hole/master/automated%20install/basic-install.sh"
    dest: "/etc/pihole/pihole-install.sh"
    mode: u+rwx
  when: not pihole_installed

- name: Run pihole install script
  shell: /etc/pihole/pihole-install.sh --unattended
  when: not pihole_installed

- name: Delete pihole install script
  file:
    path: "/etc/pihole/pihole-install.sh"
    state: absent

- include_tasks: updatelists.yml
